version: '3.8'
networks:
    react_network:

services:
  react-app:
    build: 
      context: ./test
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    container_name: react_prod
    networks:
      - react_network

  server-api:
    build: 
      context: ./serverapi
      dockerfile: Dockerfile
    container_name: server-api
    restart: always
    networks:
      - react_network

