version: '3.8'
networks:
  nginx_network:
    driver: bridge

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      # - frontend
      - nginx_network

  react-app1:
    build: 
      context: ./test
      dockerfile: Dockerfile.prod
    container_name: react_prod
    networks:
      - nginx_network
    

  server-api_prod:
    build: 
      context: ./serverapi
      dockerfile: Dockerfile.prod
    container_name: server-api_prod
    restart: always
    networks:
      - nginx_network

  react-app2:
    build: 
      context: ./test
      dockerfile: Dockerfile.dev
    container_name: react_dev
    networks:
      - nginx_network
    

  server-api_dev:
    build: 
      context: ./serverapi
      dockerfile: Dockerfile.dev
    container_name: server-api_dev
    restart: always
    networks:
      - nginx_network  