version: '3.8'

services:
  react-app:
    build: 
      context: ./test
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    container_name: react_prod
    

  server-api:
    build: 
      context: ./serverapi
      dockerfile: Dockerfile
    container_name: server-api
    restart: always
    links:
      - react-app


